package net.thumbtack.school.hospital.validator.exception;

public enum HospitalErrorCode {

    DUPLICATE_USER,
    WRONG_LOGIN,
    ARGUMENT_MISMATCH_ERROR,
    CONSTRAINT_VIOLATION_ERROR,
    DUPLICATE_ROOM,
    WRONG_ID,
    WRONG_SPECIALITY,
    WRONG_PASSWORD,
    METHOD_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR,
    HTTP_MESSAGE_NOT_READABLE,
    WRONG_USER_TYPE,
    VALIDATION_ERROR,
    AUTHORISATION_ERROR,
    CAN_NOT_ADD_PATIENT_TO_APPOINTMENT,
    CAN_NOT_CANCEL_APPOINTMENT,
    CAN_NOT_ADD_PATIENT_TO_COMMISSION,
    CAN_NOT_FIND_USER,
    CAN_NOT_UPDATE_SCHEDULE
}
